name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Chrome browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Download ChromeDriver
        run: |
          wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/${{ env.CHROME_VERSION }}/chromedriver_linux64.zip
          unzip chromedriver.zip -d chromedriver
          chmod +x chromedriver/chromedriver
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Execute Test Cases
        run: dotnet test --no-restore --verbosity normal
      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './Todoist-BDD/bin/Debug/net6.0/allure-results'
          keep_files: true
          user_name: wiil4
          user_email: aln.wil4@outlook.es
          publish_branch: gh_page
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: './Todoist-BDD/bin/Debug/net6.0/allure-results'
          gh_pages: gh-pages
          allure_report: allure-report
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report
      - name: Run Selenium tests
        run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          export CHROME_DRIVER_PATH=./chromedriver/chromedriver
          dotnet test
